# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-03 10:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0002_examroutine'),
    ]

    operations = [
        migrations.AddField(
            model_name='examroutine',
            name='exam_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
