# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-28 21:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_userprofile_is_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.Student'),
        ),
    ]
