# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-28 21:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_userprofile_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='librarian',
            name='birthday',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
