# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-28 21:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20180128_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='librarian',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
    ]
