# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-28 22:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20180128_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='librarian',
            name='gender',
            field=models.CharField(blank=True, default='male', max_length=255, null=True),
        ),
    ]
